
;; music-db.scm
; The music database in representation 1
(define *music-db*
  '(((Respect) (Aretha Franklin) 1967 Soul)
    ((My Way) (Frank Sinatra) 1969 Vocal)
    ((My Way) (Sex Pistols) 1979 Rock)
    ((The Harder They Come) (Jimmy Cliff) 1972 Reggae)
    ((The Ketchup Song) (Las Ketchup) 2002 Pop)
    ((My Way) (The Muppets) 1978 Novelty)
    ((45) (Elvis Costello) 2002 Rock)
    ((Dy-Na-Mi-Tee) (Ms. Dynamite) 2002 Hip-Hop)
    ((911 Is A Joke) (Public Enemy) 1990 Rap)
    ((Numb) (U2) 1993 Rock)
    ((Lose Yourself) (Eminem) 2002 Rap)
    ((Louie Louie) (Iggy Pop) 1993 Rock)
    ((Watching The Detectives) (Elvis Costello) 1977 Rock)
    ((Roll Down the Line) (The Walkmen) 2002 Rock)
    ((Spooky Girlfriend) (Elvis Costello) 2002 Rock)
    ((Throw Away Your Television) (Red Hot Chili Peppers) 2002 Rock)
    ((Across the Universe) (The Beatles) 1970 Rock)
    ((The Fly) (U2) 1991 Rock)
    ((Antistar) (Massive Attack) 2003 Rock)
    ((Hate To Say I Told You So) (The Hives) 2000 Rock)
    ((The Blues Is My Business) (Etta James) 2003 Blues)
    ((Even Better Than The Real Thing) (U2) 1991 Rock)
    ((Special Cases) (Massive Attack) 2003 Rock)
    ((Built For Comfort) (Howlin Wolf) 1966 Blues)
    ((Little Red Rooster) (The Rolling Stones) 1965 Rock)
    ((Go With The Flow) (Queens Of The Stone Age) 2002 Rock)
    ((Alison) (Elvis Costello) 1977 Rock)
    ((One Tree Hill) (U2) 1987 Rock)
    ((Hella Good) (No Doubt) 2001 Ska)
    ((Myxamatosis) (Radiohead) 2003 Electronic)
    ((Waiting For The End Of The World) (Elvis Costello) 1977 Rock)
    ((Gloria) (Patti Smith) 1975 Rock)
    ((Lonesome Day Blues) (Bob Dylan) 2001 Folk)
    ((Crawling To The USA) (Elvis Costello) 1978 Rock)
    ((The Harder They Come) (Joe Strummer) 2000 Rock)
    ((Shut Up) (The Black Eyed Peas) 2003 Rap)
    ((Lucy In The Sky With Diamonds) (The Beatles) 1967 Rock)				
    ((Louie Louie) (The Clash) 1984 Rock)
    ((1979) (The Smashing Pumpkins) 1995 Rock)
    ((Without Me) (Eminem) 2002 Rap)
    ((Little Red Rooster) (Sam Cooke) 1963 R&B)
    ((Round Round) (Sugababes) 2002 Pop)
    ((Lip Service) (Elvis Costello) 1978 Rock)
    ((Date With a Night) (Yeah Yeah Yeahs) 2003 Rock)
    ((Coma Girl) (Joe Strummer) 2003 Rock)
    ((Anarchy in the UK) (Sex Pistols) 1977 Rock)
    ((Pretty Vacant) (Sex Pistols) 1977 Rock)
    ((Fantasize) (Liz Phair) 1998 Rock)
    ((United States of Whatever) (Liam Lynch) 2003 Rock)
    ((Running To Stand Still) (U2) 1987 Rock)
    ((Let It Be) (The Beatles) 1970 Rock)
    ((I Never Loved A Man) (Aretha Franklin) 1967 Soul)
    ((What It Feels Like For A Girl) (Madonna) 2000 Pop)
    ((Louie Louie) (The Kinks) 1964 Rock)
    ((Sympathy For the Strawberry) (Sonic Youth) 2002 Rock)
    ((Rich) (Yeah Yeah Yeahs) 2003 Rock)
    ((Bhindi Bhagee) (Joe Strummer) 2001 Rock)
    ((Radical Adults Lick Godhead Style) (Sonic Youth) 2002 Rock)
    ((Little Red Rooster) (The Jesus And Mary Chain) 1993 Rock)
    ((With Or Without You) (U2) 1987 Rock)
    ((Clint Eastwood) (Gorillaz) 2001 Rock)
    ((Polyester Bride) (Liz Phair) 1998 Rock)
    ((Twist And Shout) (Isley Brothers) 1962 Rock)
    ((Supernova) (Liz Phair) 1994 Rock)
    ((What Your Soul Sings) (Massive Attack) 2003 Rock)
    ((Chain of fools) (Aretha Franklin) 1967 Soul)
    ((third eye) (The Black Eyed Peas) 2003 Rap)
    ((The Chokin Kind) (Joss Stone) 2003 R&B)
    ((No No No) (Yeah Yeah Yeahs) 2003 Rock)
    ((Shut Your Mouth) (Garbage) 2001 Rock)
    ((Zoo Station) (U2) 1991 Rock)
    ((Twist And Shout) (The Beatles) 1963 Rock)
    ((When I Was Cruel No. 2) (Elvis Costello) 2002 Rock)
    ((1999) (Prince) 1983 Rock)
    ((Bohemian Like You) (The Dandy Warhols) 2000 Rock)
    ((1989) (Titiyo) 2001 Rock)
    ((Black Tongue) (Yeah Yeah Yeahs) 2003 Rock)
    ((Vogue) (Madonna) 1990 Pop)
    ((Louie Louie) (The Pretenders) 1981 Rock)
    ((Mystery Train) (Elvis Presley) 1955 Rock)
    ((God Save the Queen) (Sex Pistols) 1977 Rock)
    ((The Way I Am) (Eminem) 2000 Rap)
    ((A Drunken Punch Up At A Wedding) (Radiohead) 2003 Electronic)
    ((Maps) (Yeah Yeah Yeahs) 2003 Rock)
    ((Modern Romance) (Yeah Yeah Yeahs) 2003 Rock)
    ((Everyone Who Pretended to Like Me Is Gone) (The Walkmen) 2002 Rock)
    ((He War) (Cat Power) 2003 Rock)
    ((Beyond Belief) (Elvis Costello) 1982 Rock)
    ((Where The Streets Have No Name) (U2) 1987 Rock)
    ((Addicts Of Communication) (Randy) 2001 Rock)
    ((Elevation) (U2) 2000 Rock)
    ((Red Morning Light) (Kings of Leon) 2003 Rock)
    ((The Rock) (Etta James) 1997 Blues)
    ((Y-Control) (Yeah Yeah Yeahs) 2003 Rock)
    ((99 Luftballons) (Nena) 1983 Rock)
    ((Seed 2.0) (The Roots) 2002 Rap)
    ((The Red Rooster) (Howlin Wolf) 1962 Blues)
    ((Louie Louie) (Toots and the Maytalls) 1973 Reggae)
    ((Baby Got Going) (Liz Phair) 1998 Rock)
    ((Nu Flow) (Big Brovaz) 2002 Rap)
    ((Wake up) (The Walkmen) 2002 Rock)
    ((In My Time of Dying) (Bob Dylan) 1962 Folk)
    ((Weapon Of Choice) (Fatboy Slim) 2000 Electronic)
    ((Stronger) (Sugababes) 2002 Pop)
    ((With A Little Help From My Friends) (The Beatles) 1967 Rock)
    ((Beautiful Day) (U2) 2000 Rock)
    ((where is the love) (The Black Eyed Peas) 2003 Rap)
    ((40) (U2) 1983 Rock)
    ((Louie Louie) (Kingsmen) 1963 Oldies)
    ((Pin) (Yeah Yeah Yeahs) 2003 Rock)
    ((Whip-Smart) (Liz Phair) 1994 Rock)
    ((Because the Night) (Patti Smith) 1978 Rock)
    ((Revenge Wears No Wristwatch) (The Walkmen) 2002 Rock)
    ((7 Seconds) (Neneh Cherry) 1996 Rap)
    ((She Hates Me) (Puddle of Mudd) 2001 Rock)
    ((Sympathy for the Devil) (The Rolling Stones) 1968 Rock)))

; The music database in representation 2
(define *music-db-nr-2* 
  '((1
      (title Respect)    
      (year . 1967)
      (artist Aretha Franklin)
      (genre . Soul))
     (2
      (genre . Vocal)
      (title My Way)
      (artist Frank Sinatra)
      (year . 1969))
     (3
      (year . 1979)
      (artist Sex Pistols) 
      (title My Way)
      (genre . Rock))
     (4
      (title The Harder They Come)
      (artist Jimmy Cliff)
      (year . 1972)
      (genre . Reggae))
     (5
      (title The Ketchup Song)
      (artist Las Ketchup)
      (year . 2002)
      (genre . Pop))
     (6
      (title My Way)
      (artist The Muppets)
      (year . 1978)
      (genre . Novelty))
     (7 
      (year . 2002)
      (artist Elvis Costello)
      (genre . Rock)   
      (title 45))
     (8
      (title Dy-Na-Mi-Tee)
      (artist Ms. Dynamite)
      (year . 2002)
      (genre . Hip-Hop))
     (9
      (title 911 Is A Joke)
      (artist Public Enemy)
      (year . 1990)
      (genre . Rap))
     (10
      (artist U2)
      (year . 1993) 
      (title Numb)
      (genre . Rock))
     (11
      (title Lose Yourself)
      (artist Eminem)
      (year . 2002)
      (genre . Rap))
     (12
      (title Louie Louie)
      (year . 1993)  
      (artist Iggy Pop)  
      (genre . Rock))
     (13
      (genre . Rock)
      (title Watching The Detectives)
      (artist Elvis Costello)
      (year . 1977))
     (14
      (title Roll Down the Line)
      (artist The Walkmen)
      (year . 2002)
      (genre . Rock))
     (15
      (title Spooky Girlfriend)
      (artist Elvis Costello)
      (year . 2002)
      (genre . Rock))
     (16
      (title Throw Away Your Television)
      (artist Red Hot Chili Peppers)
      (year . 2002)
      (genre . Rock))
     (17
      (title Across the Universe)
      (artist The Beatles)
      (year . 1970)
      (genre . Rock))
     (18
      (year . 1991) 
      (title The Fly) 
      (artist U2)
      (genre . Rock))
     (19
      (title Antistar)
      (artist Massive Attack)
      (year . 2003)
      (genre . Rock))
     (20
      (title Hate To Say I Told You So)
      (artist The Hives)
      (year . 2000)
      (genre . Rock))
     (21
      (title The Blues Is My Business)
      (artist Etta James)
      (year . 2003)
      (genre . Blues))
     (22
      (title Even Better Than The Real Thing)
      (artist U2)
      (year . 1991)
      (genre . Rock))
     (23
      (title Special Cases)
      (artist Massive Attack)
      (year . 2003)
      (genre . Rock))
     (24
      (title Built For Comfort)
      (artist Howlin Wolf)
      (year . 1966)
      (genre . Blues))
     (25
      (title Little Red Rooster)
      (artist The Rolling Stones)
      (year . 1965)
      (genre . Rock))
     (26
      (title Go With The Flow)
      (artist Queens Of The Stone Age)
      (year . 2002)
      (genre . Rock))
     (27
      (title Alison)
      (artist Elvis Costello)
      (year . 1977)
      (genre . Rock))
     (28 
      (title One Tree Hill)
      (artist U2) 
      (year . 1987) 
      (genre . Rock))
     (29
      (title Hella Good)
      (artist No Doubt)
      (year . 2001)
      (genre . Ska))
     (30
      (title Myxamatosis)
      (artist Radiohead)
      (year . 2003)
      (genre . Electronic))
     (31
      (title Waiting For The End Of The World)
      (artist Elvis Costello)
      (year . 1977)
      (genre . Rock))
     (32
      (title Gloria)
      (artist Patti Smith)
      (year . 1975)
      (genre . Rock))
     (33
      (title Lonesome Day Blues)
      (artist Bob Dylan)
      (year . 2001)
      (genre . Folk))
     (34
      (title Crawling To The USA)
      (artist Elvis Costello)
      (year . 1978)
      (genre . Rock))
     (35
      (title The Harder They Come)
      (artist Joe Strummer)
      (year . 2000)
      (genre . Rock))
     (36
      (title Shut Up)
      (artist The Black Eyed Peas)
      (year . 2003)
      (genre . Rap))
     (37
      (title Lucy In The Sky With Diamonds)
      (artist The Beatles)
      (year . 1967)
      (genre . Rock))
     (38
      (title Louie Louie)
      (artist The Clash)
      (year . 1984)
      (genre . Rock))
     (39
      (title 1979)
      (artist The Smashing Pumpkins)
      (year . 1995)
      (genre . Rock))
     (40
      (artist Eminem) 
      (year . 2002) 
      (genre . Rap)
      (title Without Me))
     (41
      (title Little Red Rooster)
      (artist Sam Cooke)
      (year . 1963)
      (genre . R&B))
     (42
      (title Round Round)
      (artist Sugababes)
      (year . 2002)
      (genre . Pop))
     (43
      (title Lip Service)
      (year . 1978)
      (artist Elvis Costello)
      (genre . Rock))
     (44
      (title Date With a Night)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (45
      (title Coma Girl)
      (artist Joe Strummer)
      (year . 2003)
      (genre . Rock))
     (46
      (title Anarchy in the UK)
      (artist Sex Pistols)
      (year . 1977)
      (genre . Rock))
     (47
      (title Pretty Vacant)
      (artist Sex Pistols)
      (year . 1977)
      (genre . Rock))
     (48
      (title Fantasize)
      (artist Liz Phair)
      (year . 1998)
      (genre . Rock))
     (49
      (title United States of Whatever)
      (artist Liam Lynch)
      (year . 2003)
      (genre . Rock))
     (50
      (title Running To Stand Still)
      (artist U2)
      (year . 1987)
      (genre . Rock))
     (51 
      (genre . Rock)
      (title Let It Be) 
      (year . 1970)
      (artist The Beatles))
     (52
      (title I Never Loved A Man)
      (artist Aretha Franklin)
      (year . 1967)
      (genre . Soul))
     (53
      (title What It Feels Like For A Girl)
      (artist Madonna)
      (year . 2000)
      (genre . Pop))
     (54
      (title Louie Louie)
      (artist The Kinks)
      (year . 1964)
      (genre . Rock))
     (55
      (title Sympathy For the Strawberry)
      (artist Sonic Youth)
      (year . 2002)
      (genre . Rock))
     (56
      (title Rich) 
      (year . 2003)
      (artist Yeah Yeah Yeahs)
      (genre . Rock))
     (57
      (title Bhindi Bhagee)
      (artist Joe Strummer)
      (year . 2001)
      (genre . Rock))
     (58
      (title Radical Adults Lick Godhead Style)
      (artist Sonic Youth)
      (year . 2002)
      (genre . Rock))
     (59
      (title Little Red Rooster)
      (artist The Jesus And Mary Chain)
      (year . 1993)
      (genre . Rock))
     (60
      (title With Or Without You)
      (artist U2)
      (year . 1987)
      (genre . Rock))
     (61
      (title Clint Eastwood)
      (artist Gorillaz)
      (year . 2001)
      (genre . Rock))
     (62
      (title Polyester Bride)
      (artist Liz Phair)
      (year . 1998)
      (genre . Rock))
     (63  
      (artist Isley Brothers)
      (title Twist And Shout)
      (year . 1962)
      (genre . Rock))
     (64  
      (artist Liz Phair)
      (title Supernova)
      (year . 1994)
      (genre . Rock))
     (65
      (title What Your Soul Sings)
      (artist Massive Attack)
      (year . 2003)
      (genre . Rock))
     (66
      (title Chain of fools)
      (artist Aretha Franklin)
      (year . 1967)
      (genre . Soul))
     (67
      (title third eye)
      (artist The Black Eyed Peas)
      (year . 2003)
      (genre . Rap))
     (68
      (title The Chokin Kind)
      (artist Joss Stone)
      (year . 2003)
      (genre . R&B))
     (69
      (title No No No)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (70
      (title Shut Your Mouth)
      (artist Garbage)
      (year . 2001)
      (genre . Rock))
     (71
      (artist U2) 
      (year . 1991)
      (title Zoo Station) 
      (genre . Rock))
     (72 
      (year . 1963)
      (title Twist And Shout)
      (artist The Beatles)
      (genre . Rock))
     (73
      (title When I Was Cruel No. 2)
      (artist Elvis Costello)
      (year . 2002)
      (genre . Rock))
     (74 
      (artist Prince) 
      (year . 1983) 
      (genre . Rock)
      (title 1999))
     (75
      (title Bohemian Like You)
      (artist The Dandy Warhols)
      (year . 2000)
      (genre . Rock))
     (76 
      (title 1989)
      (artist Titiyo)
      (year . 2001) 
      (genre . Rock))
     (77
      (title Black Tongue)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (78 
      (title Vogue)
      (year . 1990) 
      (artist Madonna) 
      (genre . Pop))
     (79
      (title Louie Louie)
      (artist The Pretenders)
      (year . 1981)
      (genre . Rock))
     (80
      (title Mystery Train)
      (artist Elvis Presley)
      (year . 1955)
      (genre . Rock))
     (81
      (title God Save the Queen)  
      (year . 1977)
      (artist Sex Pistols)
      (genre . Rock))
     (82   
      (genre . Rap)
      (title The Way I Am)
      (artist Eminem)
      (year . 2000))
     (83
      (title A Drunken Punch Up At A Wedding)
      (artist Radiohead)
      (year . 2003)
      (genre . Electronic))
     (84
      (title Maps)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (85
      (title Modern Romance)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (86
      (title Everyone Who Pretended to Like Me Is Gone)
      (artist The Walkmen)
      (year . 2002)
      (genre . Rock))
     (87 
      (artist Cat Power)
      (title He War)
      (year . 2003) 
      (genre . Rock))
     (88
      (title Beyond Belief)
      (artist Elvis Costello)
      (year . 1982)
      (genre . Rock))
     (89
      (title Where The Streets Have No Name)
      (artist U2)
      (year . 1987)
      (genre . Rock))
     (90
      (title Addicts Of Communication)
      (artist Randy)
      (year . 2001)
      (genre . Rock))
     (91 
      (year . 2000)
      (title Elevation) 
      (artist U2)
      (genre . Rock))
     (92
      (title Red Morning Light)
      (artist Kings of Leon)
      (year . 2003)
      (genre . Rock))
     (93
      (title The Rock)
      (artist Etta James)
      (year . 1997)
      (genre . Blues))
     (94
      (title Y-Control)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (95
      (title 99 Luftballons)
      (artist Nena)
      (year . 1983)
      (genre . Rock))
     (96 
      (artist The Roots)
      (title Seed 2.0) 
      (year . 2002) 
      (genre . Rap))
     (97
      (title The Red Rooster)
      (artist Howlin Wolf)
      (year . 1962)
      (genre . Blues))
     (98
      (title Louie Louie)
      (artist Toots and the Maytalls)
      (year . 1973)
      (genre . Reggae))
     (99
      (title Baby Got Going)
      (artist Liz Phair)
      (year . 1998)
      (genre . Rock))
     (100
      (title Nu Flow) 
      (year . 2002)
      (artist Big Brovaz)
      (genre . Rap))
     (101
      (title Wake up)
      (artist The Walkmen)
      (year . 2002)
      (genre . Rock))
     (102
      (title In My Time of Dying)
      (artist Bob Dylan)
      (year . 1962)
      (genre . Folk))
     (103 
      (artist Fatboy Slim)
      (title Weapon Of Choice)
      (year . 2000)
      (genre . Electronic))
     (104  
      (year . 2002)
      (title Stronger)
      (artist Sugababes)
      (genre . Pop))
     (105
      (title With A Little Help From My Friends)
      (artist The Beatles)
      (year . 1967)
      (genre . Rock))
     (106
      (artist U2)
      (year . 2000)
      (title Beautiful Day) 
      (genre . Rock))
     (107
      (title where is the love)
      (artist The Black Eyed Peas)
      (year . 2003)
      (genre . Rap))
     (108 
      (title 40) 
      (artist U2)
      (year . 1983)
      (genre . Rock))
     (109
      (title Louie Louie)
      (artist Kingsmen)
      (year . 1963)
      (genre . Oldies))
     (110
      (title Pin)
      (artist Yeah Yeah Yeahs)
      (year . 2003)
      (genre . Rock))
     (111
      (title Whip-Smart)
      (artist Liz Phair)
      (year . 1994)
      (genre . Rock))
     (112
      (title Because the Night)
      (artist Patti Smith)
      (year . 1978)
      (genre . Rock))
     (113
      (title Revenge Wears No Wristwatch)
      (artist The Walkmen)
      (year . 2002)
      (genre . Rock))
     (114   
      (year . 1996)
      (title 7 Seconds)
      (artist Neneh Cherry)
      (genre . Rap))
     (115   
      (artist Puddle of Mudd)
      (title She Hates Me)
      (year . 2001)
      (genre . Rock))
     (116
      (title Sympathy for the Devil)
      (artist The Rolling Stones)
      (year . 1968)
      (genre . Rock))))